Traceback (most recent call last):
  File "C:\Users\Parth\Desktop\iris\pipeline.py", line 38, in <module>
    wandb.log(report['accuracy'])
  File "C:\ProgramData\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 436, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 1982, in log
    self._log(data=data, step=step, commit=commit)
  File "C:\ProgramData\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 1700, in _log
    raise TypeError("wandb.log must be passed a dictionary")
TypeError: wandb.log must be passed a dictionary
